454 save read prices
magento/storefront-pricing-ce pull request #2
Opened 2020-12-09 11:05 UTC by lykhachov

### Description (*)

### Related Pull Requests

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/catalog-storefront/issues/457

### Questions or comments

### Code Review Checklist (*)

- [ ] Story AC is completed
- [ ] proposed changes correspond to [Magento Technical Vision](https://devdocs.magento.com/guides/v2.2/coding-standards/technical-guidelines.html)
- [ ] new or changed code is covered with web-api/integration tests (if applicable)
- [ ] no backward incompatible changes

2020-12-15 21:11 UTC, mslabko requested changes

2020-12-15 21:11 UTC, mslabko commented on app/code/Magento/PricingStorefront/Console/Command/Init.php
> + * Command for search service minimum config set up
remove "search" from naming

2020-12-15 21:11 UTC, mslabko commented on app/code/Magento/PricingStorefront/Console/Command/Init.php
> +                        'id' => 'default',
use PriceBookRepository::DEFAULT_PRICE_BOOK_ID instead
move related logic to the new method with a meaningful name, e.g. "createefaultPriceBook"

2020-12-15 21:11 UTC, mslabko commented on app/code/Magento/PricingStorefront/Console/Command/Init.php
> +    {
Could you please add configuration for "env.php" file similar to what we have in search service?
So, with the execution of this command, we will be able to provide host, db and other information to setup connection to DB

This can be extracted to a separate task

2020-12-15 21:11 UTC, mslabko commented on app/code/Magento/PricingStorefront/etc/db_schema.xml
> +        <column xsi:type="text" name="id" nullable="true" comment="Price Book ID"/>
Do we have case, when the price book id may be duplicated? Looks like we should remove "row_id" field and use "id" as primary key

2020-12-15 21:11 UTC, mslabko commented on app/code/Magento/PricingStorefront/etc/db_schema.xml
> +        <column xsi:type="text" name="website_ids" nullable="true" comment="Website IDs"/>
Looks like we can utilize "JSON" type to manipulate with array and improove scope validation in \Magento\PricingStorefront\Model\PriceBookRepository::validatePriceBookUnique.

We can have a son column "scopes" with {"w": [], "cg": []} structure and create index on both fields

This can be extracted to a separate task ^^

2020-12-15 21:11 UTC, mslabko commented on app/code/Magento/PricingStorefront/etc/db_schema.xml
> +        <column xsi:type="text" name="product_id" nullable="false" comment="Product ID"/>
please, rename to "entity_id" since we have to store not only products, but option prices as well

2020-12-15 21:11 UTC, mslabko commented on app/code/Magento/PricingStorefront/etc/db_schema.xml
> +        <column xsi:type="text" name="parent_id" nullable="true" comment="Parent Price Book ID"/>
add index to "parent_id" field

2020-12-15 21:11 UTC, mslabko commented on app/code/Magento/PricingStorefront/etc/db_schema.xml
> +                    referenceColumn="row_id" onDelete="CASCADE"/>
Lets rename "pricebook_row_id" to "pricebook_id"
please, add index to fields, used in requests: product_id + pricebook_id. Probably composite index will be better - need to check cases

2020-12-15 21:11 UTC, mslabko commented on app/code/Magento/PricingStorefront/Model/PriceRepository.php
> +    public function get(string $condition): array
need to use a more strict approach to prevent SQL injection. 
Maybe pass array to be able work with placeholder

2020-12-16 01:01 UTC, mslabko requested changes

2020-12-16 01:01 UTC, mslabko commented on app/code/Magento/PricingStorefront/Model/PriceBookRepository.php
> +        foreach ($priceBook as $priceBook) {
fix typo: Variable 'priceBook' is already used as an array expression

2020-12-16 01:01 UTC, mslabko commented on app/code/Magento/PricingStorefront/Model/PriceBookRepository.php
> +            ->where(join(' OR ', $cond));
[EA] 'join(...)' is an alias function, consider using 'implode(...)' instead.

2020-12-16 01:01 UTC, mslabko commented on app/code/Magento/PricingStorefront/Model/PriceRepository.php
> +     * Delete prices by specified condition.
fix description

2020-12-16 01:01 UTC, mslabko commented on app/code/Magento/PricingStorefront/Model/PricingService.php
> +        if ($request instanceof PriceBookCreateRequestInterface) {
Due to there is no common logic, I suggest to split into 3 methods and remove if statement (argument should has a correct type)

2020-12-16 01:01 UTC, mslabko commented on app/code/Magento/PricingStorefront/Model/PricingService.php
> +                    'code' => '0',
please, move 0/1 to private constants, e.g STATUS_SUCCES = 0

2020-12-16 01:01 UTC, mslabko commented on app/code/Magento/PricingStorefront/Model/PricingService.php
> +        } catch (\ErrorException|\InvalidArgumentException $e) {
Let's use "Throwable" type to catch all errors

2020-12-16 01:01 UTC, mslabko commented on app/code/Magento/PricingStorefront/Model/PricingService.php
> +        $response = $this->assignPricesResponseFactory->create();
Please, fix response type

2020-12-16 01:01 UTC, mslabko commented on dev/tools/build-ce.php
> +<?php
Do we have cases when we need this for standalone installation? IF no, please delete it

2020-12-16 08:22 UTC, lykhachov commented on app/code/Magento/PricingStorefront/etc/db_schema.xml
> +        <column xsi:type="text" name="id" nullable="true" comment="Price Book ID"/>
the case I had in mind was: what if we change id generation algorithm to another somewhere in midway. If it's couldn't be like that, then yes row_id should be removed

2020-12-16 15:38 UTC, lykhachov commented on app/code/Magento/PricingStorefront/Console/Command/Init.php
> +    {
created separate task

2020-12-16 15:38 UTC, lykhachov commented on app/code/Magento/PricingStorefront/etc/db_schema.xml
> +        <column xsi:type="text" name="website_ids" nullable="true" comment="Website IDs"/>
created separate task

2020-12-16 15:46 UTC, mslabko commented
@magento run all tests

2020-12-16 18:24 UTC, mslabko requested changes

2020-12-16 18:24 UTC, mslabko commented on app/code/Magento/PricingStorefront/Model/PriceManagement.php
> +            if (in_array($key, $this->getPriceType())) {
please, add 3d argument as a "true"

2020-12-16 18:24 UTC, mslabko commented on app/code/Magento/PricingStorefront/Model/PriceManagement.php
> +                $parentId = $priceBook[PriceBookRepository::KEY_PARENT_ID] ?? null;
There is no such constant PriceBookRepository::KEY_PARENT_ID

2020-12-16 18:24 UTC, mslabko commented on app/code/Magento/PricingStorefront/Model/PriceManagement.php
> +                    // compare price with existing parent price and if prices the same - skip update
Here is a potential problem that can be with the next case:
- assign price $5 to PB 1
- assign price $5 to PB 2 (parent: PB1)
- assign price $10 to PB 1

Expected: $10 for PB1, $5 for PB2
Actual: $10 for PB1 and PB2

Looks like we do not have an easy way to fix it and for now we can avoid this optimisation

2020-12-16 18:24 UTC, mslabko commented on app/code/Magento/PricingStorefront/Model/PriceManagement.php
> +    public function assignPrice(string $bookId, array $price, ?string $parentId = null) : array
Could you please describe in descriptionn the business logic of price assignment work?

2020-12-16 18:24 UTC, mslabko commented on app/code/Magento/PricingStorefront/Model/PriceRepository.php
> +namespace Magento\PricingStorefront\Model;
IT's better to distinguish business logic and work with the data retreiving  and create one more namespace for repository classes

2020-12-16 18:24 UTC, mslabko commented on app/code/Magento/PricingStorefront/Model/PriceManagement.php
> +                    // if new price different as actual but same as parent price - remove actual
The same potential problem, what we have in "compare price with existing parent price"
Maybe it's better to remove this and simplify price assignment ?

2020-12-16 18:32 UTC, mslabko commented on app/code/Magento/PricingStorefront/etc/db_schema.xml
> +<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
please, check error:
```
  [Magento\Framework\Exception\LocalizedException]
  The XML in file "/var/www/html/app/code/Magento/PricingStorefront/etc/db_sc
  hema.xml" is invalid:
  Element 'column', attribute 'unsigned': The attribute 'unsigned' is not allowed.
  Line: 13

  Element 'column', attribute 'identity': The attribute 'identity' is not allowed.
  Line: 13```

2020-12-17 09:39 UTC, lykhachov commented
@magento run Integration Tests

2020-12-18 17:32 UTC, mslabko commented
@magento run all tests

2020-12-18 18:20 UTC, mslabko commented
@magento import pr to magento-commerce/storefront-pricing-ce

2020-12-18 18:21 UTC, magento-engcom-team commented
@mslabko the pull request successfully imported.

2020-12-21 07:32 UTC, closed without merging